<%
  # Use the runlist, attributes and other settings defined in node.json to
  # ensure .kitchen.yml runs against the exact same configuration as Vagrantfile.
  require 'json'
  if !File.exist?('node.json')
    puts 'Aborting .kitchen.yml: required node.json does not exist' unless File.exist?('node.json')
    exit
  else
    node = JSON.parse(File.read('node.json'))
  end
%>
---
driver:
  name: vagrant
  network:
    - [ 'private_network', {ip: "<%= node['vm']['ip_address'] %>"} ]

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: <%= node["run_list"] %>
    attributes: <%= node["attributes"].to_json %>
